[package]
name = "roblox_to_godot_project_proc_macro"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2 = "1.0.93"
syn = { version = "2.0.96", features = ["full"] }

[lib]
proc-macro = true